export enum Keyword {
  const = "const",
  true = "true",
  false = "false",
  null = "null",
  ret = "ret",
  if = "if",
  elif = "elif",
  else = "else",
  while = "while",
  for = "for",
  continue = "continue",
  break = "break",
  jmp = "jmp",
  map = "map",
}

export const KEYWORDS: string[] = [
  Keyword.const,
  Keyword.true,
  Keyword.false,
  Keyword.null,
  Keyword.ret,
  Keyword.if,
  Keyword.elif,
  Keyword.else,
  Keyword.while,
  Keyword.for,
  Keyword.continue,
  Keyword.break,
  Keyword.jmp,
  Keyword.map,
];
